[phases.setup]
nixPkgs = ["python313", "python313Packages.pip"]

[phases.install]
cmds = ["pip3 install -r backend/requirements.txt"]

[phases.build]
cmds = [
  "cd backend && python3 manage.py collectstatic --no-input",
  "cd backend && python3 manage.py migrate --no-input"
]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
