[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = [
  "python3 -m venv /app/venv",
  "/app/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "/app/venv/bin/python manage.py collectstatic --no-input",
  "/app/venv/bin/python manage.py migrate --no-input"
]

[start]
cmd = "/app/venv/bin/gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 60"
