from django.contrib.auth import authenticate
from django.contrib.auth.password_validation import validate_password
from rest_framework import serializers
from rest_framework.exceptions import AuthenticationFailed
from rest_framework_simplejwt.tokens import RefreshToken
from .models import CustomUser


class RegisterSerializer(serializers.ModelSerializer):
    """
    Serializer for user registration.
    Validates:
      - Email is unique
      - Password matches confirmation
      - Password is strong enough (Django's built-in validators)
    """

    # These are "write-only" fields - we accept them from input,
    # but never send them back in the response (security!)
    password = serializers.CharField(
        write_only=True,
        required=True,
        min_length=8,
        style={"input_type": "password"},
        validators=[validate_password],  # Use Django's built-in password rules
        error_messages={
            "min_length": "Password must be at least 8 characters long.",
        },
    )
    password_confirm = serializers.CharField(
        write_only=True,
        required=True,
        min_length=8,
        style={"input_type": "password"},
    )

    # These are "read-only" - generated by us, not from user input
    access_token = serializers.CharField(read_only=True)
    refresh_token = serializers.CharField(read_only=True)
    message = serializers.CharField(read_only=True)

    class Meta:
        model = CustomUser
        fields = [
            "id",
            "email",
            "first_name",
            "last_name",
            "password",
            "password_confirm",
            "access_token",
            "refresh_token",
            "message",
        ]

    def validate_email(self, value):
        """
        Field-level validation for email.
        Explicitly checks for duplicates (DB unique constraint also catches this,
        but this gives a friendlier error message).
        """
        if CustomUser.objects.filter(email__iexact=value).exists():
            raise serializers.ValidationError(
                "A user with this email address is already registered."
            )
        return value.lower()  # Store all emails lowercase for consistency

    def validate(self, data):
        """
        Object-level validation - has access to ALL fields.
        Perfect for checking password confirmation match.
        """
        if data["password"] != data["password_confirm"]:
            raise serializers.ValidationError(
                {"password_confirm": "Passwords do not match. Please try again."}
            )
        return data

    def create(self, validated_data):
        """
        Actually create the user after all validation passes.
        Also auto-generates JWT tokens so user is logged in after registering!
        """
        # Remove password_confirm - we don't save that to DB
        validated_data.pop("password_confirm", None)

        # Extract password so we can use set_password() to HASH it
        password = validated_data.pop("password")

        # Create the user object (in memory)
        user = CustomUser(**validated_data)

        # HASH THE PASSWORD (critical - never store plaintext!)
        user.set_password(password)

        # Save to database
        user.save()

        # Generate JWT tokens so user is logged in immediately
        refresh = RefreshToken.for_user(user)

        # Attach tokens and success message to the returned object
        user.access_token = str(refresh.access_token)
        user.refresh_token = str(refresh)
        user.message = "User registered successfully."

        return user


class LoginSerializer(serializers.Serializer):
    """
    Serializer for user LOGIN (no ModelSerializer - we're not creating anything).
    Validates credentials and returns user + JWT tokens.
    """

    email = serializers.EmailField(required=True)
    password = serializers.CharField(
        required=True,
        write_only=True,
        style={"input_type": "password"},
    )

    # Read-only outputs
    access_token = serializers.CharField(read_only=True)
    refresh_token = serializers.CharField(read_only=True)
    user_id = serializers.IntegerField(read_only=True)
    email = serializers.EmailField(read_only=True)
    first_name = serializers.CharField(read_only=True)
    last_name = serializers.CharField(read_only=True)
    message = serializers.CharField(read_only=True)

    def validate(self, data):
        """
        Validate login credentials using Django's authenticate().
        This is the SAFE way - it handles password hashing comparison for us,
        and protects against timing attacks.
        """
        email = data.get("email", "").lower().strip()
        password = data.get("password", "")

        if not email or not password:
            raise serializers.ValidationError(
                "Both email and password are required."
            )

        # Django's authenticate() checks:
        #   1. Does user with this email exist?
        #   2. Is user.is_active == True?
        #   3. Does password_hash match?
        user = authenticate(
            request=self.context.get("request"),
            username=email,  # Our USERNAME_FIELD is email, so we pass email here
            password=password,
        )

        if user is None:
            # Don't reveal WHICH was wrong (email vs password) - security best practice
            raise AuthenticationFailed(
                "Invalid login credentials. Please check your email and password."
            )

        if not user.is_active:
            raise AuthenticationFailed(
                "This account has been disabled. Please contact support."
            )

        # Generate JWT tokens
        refresh = RefreshToken.for_user(user)

        # Return everything the frontend needs
        return {
            "user_id": user.id,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "access_token": str(refresh.access_token),
            "refresh_token": str(refresh),
            "message": "Login successful.",
        }


class UserProfileSerializer(serializers.ModelSerializer):
    """
    Serializer for GET /api/auth/profile/
    Returns the currently logged-in user's profile data.
    Read-only - we don't accept input on this endpoint.
    """

    full_name = serializers.CharField(source="get_full_name", read_only=True)
    date_joined = serializers.DateTimeField(format="%Y-%m-%dT%H:%M:%SZ", read_only=True)
    last_login = serializers.DateTimeField(format="%Y-%m-%dT%H:%M:%SZ", read_only=True)

    class Meta:
        model = CustomUser
        fields = [
            "id",
            "email",
            "first_name",
            "last_name",
            "full_name",
            "is_active",
            "is_staff",
            "date_joined",
            "last_login",
        ]
        read_only_fields = fields  # ALL fields are read-only on this endpoint
